# Generated by Django 5.0 on 2025-10-11 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='캐릭터 이름')),
                ('description', models.TextField(verbose_name='캐릭터 설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/', verbose_name='캐릭터 이미지')),
                ('traits', models.TextField(help_text='여러 특징을 줄바꿈으로 구분', verbose_name='성격 특징')),
            ],
            options={
                'verbose_name': '캐릭터',
                'verbose_name_plural': '캐릭터들',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='질문 내용')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문들',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='답변 내용')),
                ('score', models.IntegerField(default=1, verbose_name='점수')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='personality_test.character', verbose_name='연관 캐릭터')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='personality_test.question', verbose_name='질문')),
            ],
            options={
                'verbose_name': '답변',
                'verbose_name_plural': '답변들',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personality_test.character', verbose_name='결과 캐릭터')),
            ],
            options={
                'verbose_name': '테스트 결과',
                'verbose_name_plural': '테스트 결과들',
                'ordering': ['-created_at'],
            },
        ),
    ]
